# Generated by Django 2.0 on 2017-12-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('styleId', models.CharField(max_length=32)),
                ('styleName', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('desc', models.CharField(max_length=320)),
                ('image', models.URLField()),
                ('lastEdit', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductPropImg',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('styleId', models.CharField(max_length=32)),
                ('props', models.CharField(max_length=32)),
                ('url', models.URLField()),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
            ],
        ),
    ]
