# Generated by Django 2.0 on 2017-12-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImg',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=32)),
                ('image', models.URLField()),
                ('position', models.IntegerField()),
            ],
        ),
    ]
